### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by pkerga** [williamdsw/saroo-compatibility-list#1]
I'm trying to get Sacred Pool working.

 First, I had to edit the images with the Sega Saturn Patcher.

 The game now launches but black screen after the Sega logo.

 So I'm trying to modify the play_delay and sector_delay variables.

 What is the right method?

 Is it possible to modify them without removing the SD card and modifying the config file?  Can we do it directly in the Saturn?

 How to proceed ?  Which one to modify first?  Go up by how much?

 Thank you for your help

**Comment by williamdsw** [comment]
my steps:
1) create folders for each disk (don't put them all in the same folder)
2) rename BIN/CUE extensions to bin/cue
3) update each cue file with the renamed bin file. example: "DISK.BIN" to "DISK.bin"
4) Add this config to saroocfg.txt

```
# Sacred Pools
[SG0000000 V0.900]
sector_delay=1000
play_delay=1000
```

**Comment by williamdsw** [comment]
Fixed by removing Blueretro Wireless Adapter before starting the game.
