### ISSUE TITLE
Arquivo de save do Saroo

### ISSUE THREAD

**Issue by sonik-br** [williamdsw/saroo-compatibility-list#11]
Oi William.
Por acaso voce tem o arquivo de save do seu saroo? Poderia compartilhar?
Pergunto pois estou tentando criar um banco de dados de nomes de arquivos de save, vinculados aos jogos.
O Saroo facilita fazer isso porque ele cria a memoria virtual pra cada jogo, com isso tenho acesso ao nome dos saves e ao ID do jogo vinculado.
Como voce testou uma quantidade enerme de jogos, o save do seu saroo deve estar bem completo!

**Comment by williamdsw** [comment]
[Pasta com arquivos de saves do SAROO](https://github.com/williamdsw/sst-gui/tree/master/Examples)

[Arquivo JSON com alguns jogos mapeados - bem incompleto](https://github.com/williamdsw/sst-gui/blob/master/Assets/StreamingAssets/games.json)

O projeto é em Unity se for tentar buildar.

**Comment by sonik-br** [comment]
Legal! Voce está fazendo um save tool? (pelo que entendi é isso).
Comecei a fazer um tambem. Se o seu for isso mesmo, acho que vou parar o meu projeto :)
Tá bem simples por enquanto. É um GUI para o tool que roda em linha de comando.

![image](https://github.com/user-attachments/assets/11dd79f0-fb32-4cf0-b47f-50a1dfd0a92e)

**Comment by williamdsw** [comment]
Sim, é um GUI baseado numa versão antiga do sst.exe disponibilizado pelo tpunix.
Faltam muitas funcionalidades e jogos para serem documentados.
Está sendo feito em Unity para disponibilização em MacOS e Linux além do Windows.

**Comment by sonik-br** [comment]
Muito útil essa ferramenta. Com certeza vou usar quando estiver pronta.
E obrigado por compartilhar os arquivos.
