### ISSUE TITLE
Crash Hang during attract/demo mode

### ISSUE THREAD

**Issue by retrofank** [williamdsw/saroo-compatibility-list#7]
I posted this in the official Saroo GitHub too.  

I noticed two titles so far hang after several minutes (10 mins onwards) when left idle on their demo/attract modes:

Capcom Generations 5
Street Fighter Zero 3

32GB Sandisk FAT32 micro SD card
JP NTSC VA10 Saturn Console
0.4 FW 240316 - FPGA 05

**Comment by williamdsw** [comment]
Did you tested [this configuration](https://github.com/williamdsw/saroo-configuration-list/blob/master/J/T-1246G/README.md) for SFZ 3?

**Comment by retrofank** [comment]
> Did you tested [this configuration](https://github.com/williamdsw/saroo-configuration-list/blob/master/J/T-1246G/README.md) for SFZ 3?

I didn’t use it no, since the configuration file was for sprite fixes.  I will have a look again with the configuration file

**Comment by williamdsw** [comment]
Tests:

SFZ3 with config:

[![[Sample] SAROO 1.32 (240515) - Street Fighter Zero 3 (Japan) = Intro Demonstration](https://img.youtube.com/vi/oM-RtWsKJyI/0.jpg)](https://www.youtube.com/watch?v=oM-RtWsKJyI)

Capcom Generations 5 without any config:

[![[Sample] SAROO 1.32 (240515) - Capcom Generations 5 (Japan) = Intro Demonstration](https://img.youtube.com/vi/ue5hOlbO3IY/0.jpg)](https://www.youtube.com/watch?v=ue5hOlbO3IY)

**Comment by retrofank** [comment]
Both games boot and play fine, unless you don’t leave it on the demo loop for over 10 minutes.

**Comment by williamdsw** [comment]
In the videos I leave it on demo loop for more than 10 minutes.

**Comment by retrofank** [comment]
Could not reproduce again after further tests with another SD card and updated firmware.

**Comment by retrofank** [comment]
See final post
